/* ============================================================
   EDITAL LEGÍVEL PELO APP — pontos, pesos e onde treinar

   Este arquivo é a digitalização dos MAPA-BANCA-*.md. Enquanto o
   markdown serve aos agentes, aqui o app lê a mesma informação para
   montar o Diagnóstico do edital e o cronograma: cruza PONTO DO
   EDITAL × SEU ACERTO × PESO (incidência) e diz o que estudar hoje.

   Cada ponto:
     id       identificador curto e estável (não reaproveite ids)
     banca    grupo da trilha ("I", "II", "III", "IV", "enam")
     materia  igual ao campo `materia` da unidade em data*.js
     tema     como o edital descreve o ponto (é o que aparece na tela)
     peso     1..5 = em quantos dos 5 pontos do edital da banca o tema
              aparece. É a incidência histórica que os mapas apuraram.
              `null` = ainda não mapeado (o app declara isso na tela e
              ranqueia esse ponto só pelo seu desempenho).
     onde treinar — três granularidades que se SOMAM (use as que
     couberem; o app une tudo num conjunto de questões):
       unidades: ["parte-geral"]        todas as lições da unidade
       licoes:   ["penal-juris-5"]      lições específicas
       questoes: ["emp-1","emp-2"]      questões específicas
     licoes/questoes VAZIO é informação, não erro: é o ❌ do mapa —
     ponto do edital sem nenhuma questão no app. O Cronograma mostra
     esses pontos numa lista à parte ("estude pela apostila") e nunca
     os coloca no plano de estudo, porque não há o que treinar.

   Um ponto pode repetir questão de outro (ex.: `trat-7` conta em
   "justiça de transição" e em "tratados"): o edital mesmo sobrepõe
   temas, e o diagnóstico trata cada ponto isoladamente.

   MANUTENÇÃO — quando um lote novo entra no banco, acrescente a
   lição nova ao ponto correspondente aqui. Se esquecer, o app avisa
   no console: "lições fora do edital.js". Não deixe o aviso de lado:
   lição fora daqui não entra em diagnóstico nem em cronograma.
   ============================================================ */

window.APP_EDITAL = {

  /* ==========================================================
     DPE-RJ — XXIX Concurso (FGV)
     Fonte dos pesos: MAPA-BANCA-I.md, MAPA-BANCA-II.md e
     MAPA-BANCA-III.md, que cruzaram o Conteúdo Programático
     (5 pontos por banca) com o banco de questões.
     ========================================================== */
  "dpe-rj": {
    fonte: "MAPA-BANCA-I/II/III.md · Conteúdo Programático do XXIX Concurso (FGV)",
    escala: "peso = em quantos dos 5 pontos do edital da banca o tema aparece",
    pontos: [

      /* ---------------------------- BANCA I · Direito Civil */
      { id: "civ-pg", banca: "I", materia: "Direito Civil", peso: 5,
        tema: "Parte Geral: pessoas, personalidade, LINDB, negócio jurídico, prescrição e decadência, desconsideração",
        unidades: ["parte-geral"] },
      { id: "civ-resp", banca: "I", materia: "Direito Civil", peso: 5,
        tema: "Responsabilidade civil, inclusive LGPD, Marco Civil, abandono afetivo, violência obstétrica e perda de uma chance",
        unidades: ["resp-civil"] },
      { id: "civ-fam", banca: "I", materia: "Direito Civil", peso: 5,
        tema: "Família: casamento e união estável, regime de bens, guarda, alienação parental, alimentos, filiação",
        unidades: ["familia-regime"] },
      { id: "civ-suc", banca: "I", materia: "Direito Civil", peso: 5,
        tema: "Sucessões: vocação hereditária, renúncia, exclusão, colação, petição de herança, inventário extrajudicial",
        unidades: ["sucessoes"] },
      { id: "civ-reais", banca: "I", materia: "Direito Civil", peso: 4,
        tema: "Posse e direitos reais: usucapiões especiais, laje, REURB, condomínio, vizinhança, bem de família",
        unidades: ["posse-reais"] },
      { id: "civ-obr", banca: "I", materia: "Direito Civil", peso: 4,
        tema: "Obrigações e contratos, inclusive locação (Lei 8.245/91)",
        unidades: ["obrigacoes-contratos"] },
      { id: "civ-cur", banca: "I", materia: "Direito Civil", peso: 1,
        tema: "Tutela, curatela, tomada de decisão apoiada, Estatuto da Pessoa com Deficiência e saúde mental (Lei 10.216)",
        unidades: ["curatela-epd"] },

      /* ------------------ BANCA I · Direito Processual Civil */
      { id: "dpc-comum", banca: "I", materia: "Direito Processual Civil", peso: 5,
        tema: "Procedimento comum: gratuidade, curadoria especial, revelia, provas e ônus, tutela provisória",
        unidades: ["proc-conhecimento"] },
      { id: "dpc-exec", banca: "I", materia: "Direito Processual Civil", peso: 5,
        tema: "Execução: impenhorabilidades, medidas atípicas, defesas do executado, alimentos, Fazenda Pública",
        unidades: ["impenhorabilidade"] },
      { id: "dpc-rec", banca: "I", materia: "Direito Processual Civil", peso: 5,
        tema: "Recursos, precedentes, coisa julgada, rescisória, reclamação, IRDR/IAC e mandado de segurança",
        licoes: ["coisa-julgada-1", "recursos-1"] },
      { id: "dpc-col", banca: "I", materia: "Direito Processual Civil", peso: 5,
        tema: "Tutela coletiva e processos estruturais",
        unidades: ["tutela-coletiva"] },
      { id: "dpc-esp", banca: "I", materia: "Direito Processual Civil", peso: 4,
        tema: "Procedimentos especiais: possessórias, locatícias, alimentos, juizados, busca e apreensão, inventário",
        questoes: ["dr-7"] },

      /* ---------------------- BANCA I · Direito Empresarial */
      { id: "emp-tit", banca: "I", materia: "Direito Empresarial", peso: 5,
        tema: "Títulos de crédito: aval do hipossuficiente, outorga conjugal, endosso, protesto",
        questoes: ["emp-1", "emp-2", "emp-3"] },
      { id: "emp-fal", banca: "I", materia: "Direito Empresarial", peso: 5,
        tema: "Falência e recuperação: classificação de créditos, art. 49 e trava bancária",
        questoes: ["emp-6", "soc-5"] },
      { id: "emp-soc", banca: "I", materia: "Direito Empresarial", peso: 5,
        tema: "Sociedades: limitada, S.A., desconsideração e modalidades, SLU, exclusão de sócio",
        questoes: ["soc-1", "soc-2", "soc-3", "soc-4", "soc-6", "soc-7"] },
      { id: "emp-loc", banca: "I", materia: "Direito Empresarial", peso: 3,
        tema: "Locação empresarial: renovatória, despejo, purga da mora",
        questoes: ["emp-4", "emp-5"] },
      { id: "emp-mei", banca: "I", materia: "Direito Empresarial", peso: 3,
        tema: "Empresário individual, ME/EPP/MEI e sociedade limitada unipessoal",
        licoes: [] },

      /* ---------------------- BANCA I · Direito do Consumidor */
      { id: "cdc-resp", banca: "I", materia: "Direito do Consumidor", peso: 5,
        tema: "Responsabilidade por fato e por vício do produto ou serviço e os prazos do CDC",
        licoes: ["cdc-responsabilidade-1"] },
      { id: "cdc-rel", banca: "I", materia: "Direito do Consumidor", peso: 4,
        tema: "Relação de consumo: consumidor equiparado e finalismo mitigado",
        questoes: ["rel-1", "rel-2"] },
      { id: "cdc-contr", banca: "I", materia: "Direito do Consumidor", peso: 3,
        tema: "Proteção contratual: cláusulas abusivas, direito de arrependimento, garantias",
        questoes: ["rel-3", "rel-4", "rel-5"] },
      { id: "cdc-saude", banca: "I", materia: "Direito do Consumidor", peso: 3,
        tema: "Planos de saúde, inclusive cobertura de tratamento do TEA",
        licoes: ["planos-saude-1"], questoes: ["vid-4"] },
      { id: "cdc-dados", banca: "I", materia: "Direito do Consumidor", peso: 3,
        tema: "Bancos de dados e cadastros, LGPD, credit scoring, cobrança indevida e devolução em dobro",
        questoes: ["dig-1", "dig-2", "dig-3", "dig-4", "dig-5", "rel-6"] },
      { id: "cdc-pub", banca: "I", materia: "Direito do Consumidor", peso: 2,
        tema: "Publicidade, oferta e práticas comerciais: oferta vinculante, publicidade enganosa e abusiva",
        licoes: ["relacao-consumo-3"], questoes: ["rel-7"] },
      { id: "cdc-ecom", banca: "I", materia: "Direito do Consumidor", peso: 2,
        tema: "Comércio eletrônico, Marco Civil da Internet (com o STF de 2025) e golpes",
        questoes: ["dig-6", "dig-7"] },
      { id: "cdc-sup", banca: "I", materia: "Direito do Consumidor", peso: 2,
        tema: "Superendividamento (Lei 14.181/2021)",
        licoes: ["cdc-responsabilidade-2"] },
      { id: "cdc-serv", banca: "I", materia: "Direito do Consumidor", peso: 3,
        tema: "Serviços públicos como relação de consumo: corte por inadimplemento, saneamento, Lei 8.987",
        questoes: ["adm-2", "adm-3", "adm-4"] },

      /* ------------- BANCA I · Criança, Adolescente e Idoso */
      { id: "inf-prot", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 5,
        tema: "Proteção integral, Sistema de Garantia de Direitos, Conselho Tutelar e curadoria especial",
        questoes: ["inf-1", "inf-2", "inf-6"] },
      { id: "inf-idoso", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 5,
        tema: "Estatuto da Pessoa Idosa: alimentos, violência, planos de saúde, medidas de proteção, crimes",
        questoes: ["inf-5", "vid-3", "vid-4", "vid-5", "vid-6"] },
      { id: "inf-escuta", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 4,
        tema: "Lei 13.431 (escuta especializada e depoimento especial) e Lei Henry Borel",
        questoes: ["vid-1", "vid-2"] },
      { id: "inf-ado", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 4,
        tema: "Adoção (modalidades, cadastro, intuitu personae) e destituição do poder familiar",
        questoes: ["inf-3", "ado-1", "ado-2", "ado-3"] },
      { id: "inf-acolh", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 2,
        tema: "Acolhimento institucional e familiar: PIA e audiências concentradas",
        questoes: ["inf-4", "ado-4"] },
      { id: "inf-educ", banca: "I", materia: "Criança, Adolescente e Idoso", peso: 3,
        tema: "Educação (creche, inclusão, bullying), TEA e BPC, ECA Digital",
        questoes: ["ado-5", "ado-6"] },

      /* ----------------------- BANCA II · Direito Penal */
      { id: "pen-pena", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Teoria da pena, dosimetria, medida de segurança e extinção da punibilidade",
        licoes: ["penal-juris-5"] },
      { id: "pen-esp", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Crimes em espécie: contra a pessoa, o patrimônio, a dignidade sexual e a Administração Pública",
        licoes: ["penal-juris-6", "penal-juris-8"] },
      { id: "pen-teoria", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Teoria do crime, princípios e lei penal no tempo e no espaço",
        licoes: ["penal-juris-3"] },
      { id: "pen-drogas", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Lei de Drogas",
        licoes: ["penal-juris-4"] },
      { id: "pen-hed", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Crimes hediondos, Maria da Penha, tortura e racismo (Lei 14.532/2023)",
        licoes: ["penal-juris-7"] },
      { id: "pen-arm", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Desarmamento, crimes de trânsito, organização criminosa e o Tema 506 do STF",
        licoes: ["penal-juris-9"] },
      { id: "pen-novas", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Leis de 2024-2026: Feminicídio (14.994), Antifacção (15.358), Vicaricídio (15.384), Bullying (14.811)",
        questoes: ["esp-7", "lex-5", "arm-4", "arm-5"] },
      { id: "pen-sum", banca: "II", materia: "Direito Penal", peso: 5,
        tema: "Súmulas, teses e atualizações de Penal e leis especiais (tema transversal da FGV)",
        licoes: ["penal-juris-1", "penal-juris-2"] },
      { id: "pen-fe", banca: "II", materia: "Direito Penal", peso: 3,
        tema: "Crimes contra a fé pública, a paz pública e a incolumidade pública; contravenções",
        licoes: [] },

      /* ------------- BANCA II · Direito Processual Penal */
      { id: "pp-prov", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Prova penal, reconhecimento de pessoas e provas ilícitas",
        licoes: ["proc-penal-juris-2"], questoes: ["cau-5"] },
      { id: "pp-cau", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Medidas cautelares, prisão e liberdade, audiência de custódia",
        licoes: ["proc-penal-juris-4"] },
      { id: "pp-proc", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Procedimentos (comum, júri e especiais), nulidades, recursos, habeas corpus e revisão criminal",
        licoes: ["proc-penal-juris-3"], questoes: ["jur-1", "jur-2", "jur-3", "jur-4"] },
      { id: "pp-comp", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Competência, ação penal e investigação criminal",
        questoes: ["comp-1", "comp-2", "comp-3", "comp-5", "comp-7"] },
      { id: "pp-prin", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Princípios, sistemas processuais, garantismo e justiça penal consensual",
        questoes: ["pp-2"] },
      { id: "pp-sum", banca: "II", materia: "Direito Processual Penal", peso: 5,
        tema: "Súmulas e teses consolidadas de Processo Penal (tema transversal da FGV)",
        licoes: ["proc-penal-juris-1"] },
      { id: "pp-jec", banca: "II", materia: "Direito Processual Penal", peso: 4,
        tema: "Juizados especiais criminais (Lei 9.099) e acordo de não persecução penal",
        questoes: ["comp-4", "comp-6"] },
      { id: "pp-lex", banca: "II", materia: "Direito Processual Penal", peso: 4,
        tema: "Maria da Penha processual, ECA infracional, interceptação telefônica e organização criminosa",
        questoes: ["jur-5", "jur-6", "jur-7", "lex-2", "lex-3", "arm-6"] },

      /* ----------- BANCA II · Direito de Execução Penal */
      { id: "ep-ppl", banca: "II", materia: "Direito de Execução Penal", peso: 5,
        tema: "Execução da pena privativa de liberdade: progressão pós-Anticrime, livramento, remição, detração",
        licoes: ["exec-penal-juris-1", "exec-penal-juris-2"] },
      { id: "ep-fal", banca: "II", materia: "Direito de Execução Penal", peso: 5,
        tema: "Faltas disciplinares, deveres e direitos do preso, RDD",
        questoes: ["fal-1", "fal-2", "fal-3", "fal-7"] },
      { id: "ep-int", banca: "II", materia: "Direito de Execução Penal", peso: 5,
        tema: "Regras internacionais (Bangkok e Mandela), ADPF 347 e a Corte IDH",
        licoes: ["exec-penal-juris-3"] },
      { id: "ep-clem", banca: "II", materia: "Direito de Execução Penal", peso: 4,
        tema: "Anistia, graça, indulto e comutação",
        questoes: ["fal-4", "fal-5"] },
      { id: "ep-mul", banca: "II", materia: "Direito de Execução Penal", peso: 3,
        tema: "Medida de segurança na execução, pena de multa, penas restritivas de direitos e sursis",
        questoes: ["pen-6", "mul-1", "mul-2", "mul-3"] },
      { id: "ep-inc", banca: "II", materia: "Direito de Execução Penal", peso: 2,
        tema: "Incidentes, excesso e desvio de execução, conversões, reabilitação e órgãos da execução",
        questoes: ["fal-6", "mul-4", "mul-5", "mul-6", "mul-7"] },

      /* ----------------------- BANCA II · Criminologia */
      { id: "cri-par", banca: "II", materia: "Criminologia", peso: 5,
        tema: "Paradigmas criminológicos: positivista, da reação social e feminista",
        licoes: ["criminologia-1"], questoes: ["cri2-1"] },
      { id: "cri-cont", banca: "II", materia: "Criminologia", peso: 5,
        tema: "Criminologias contemporâneas: queer/LGBTIfobia, racial e letalidade, feminista, direitos humanos, vitimologia",
        licoes: ["criminologia-2"] },
      { id: "cri-pol", banca: "II", materia: "Criminologia", peso: 5,
        tema: "Política criminal: abolicionismo, minimalismo, direito penal do inimigo, populismo, criminologia midiática, drogas",
        licoes: ["criminologia-3"] },
      { id: "cri-teo", banca: "II", materia: "Criminologia", peso: 5,
        tema: "Teorias sociológicas: associação diferencial, subculturas, colarinho branco, anomia, Escola de Chicago",
        questoes: ["cri2-7", "pol-4", "pol-5"] },
      { id: "cri-necro", banca: "II", materia: "Criminologia", peso: 4,
        tema: "Necropolítica, encarceramento em massa e neoliberalismo",
        questoes: ["cri2-4"] },

      /* ------------- BANCA III · Direito Constitucional */
      { id: "con-trat", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Tratados internacionais (art. 5º, §3º), supralegalidade, controle de convencionalidade, IDC, sentenças internacionais",
        questoes: ["trat-1", "trat-2", "trat-3", "trat-4", "trat-5", "trat-6"] },
      { id: "con-pc", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Poder constituinte e cláusulas pétreas",
        questoes: ["pcs-1", "pcs-2"] },
      { id: "con-controle", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Controle de constitucionalidade e interpretação constitucional",
        questoes: ["pcs-3", "pcs-4", "pcs-5", "pcs-6", "pcs-7", "const-2", "const-6"] },
      { id: "con-df", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Direitos e garantias fundamentais; direito constitucional antidiscriminatório",
        questoes: ["const-1", "const-3", "const-4", "const-5"] },
      { id: "con-seg", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Segurança pública, política penitenciária e direito à segurança",
        questoes: ["seg-1", "seg-2", "seg-3", "seg-4"] },
      { id: "con-social", banca: "III", materia: "Direito Constitucional", peso: 4,
        tema: "Ordem social; justiça social, inclusão e participação social",
        questoes: ["seg-5", "seg-6"] },
      { id: "con-trans", banca: "III", materia: "Direito Constitucional", peso: 3,
        tema: "Justiça de transição, memória e verdade",
        questoes: ["trat-7"] },
      { id: "con-fej", banca: "III", materia: "Direito Constitucional", peso: 3,
        tema: "Funções essenciais à Justiça e a Defensoria Pública na Constituição",
        questoes: ["dp-1", "dp-3"] },
      { id: "con-com", banca: "III", materia: "Direito Constitucional", peso: 3,
        tema: "Comunicação social e regulação da mídia",
        questoes: ["seg-7"] },
      { id: "con-amb", banca: "III", materia: "Direito Constitucional", peso: 3,
        tema: "Meio ambiente na Constituição, resíduos sólidos, saneamento e água",
        questoes: ["adm-5", "adm-6"] },
      { id: "con-org", banca: "III", materia: "Direito Constitucional", peso: 3,
        tema: "Organização do Estado e dos Poderes; intervenção federal e estadual",
        licoes: [] },
      { id: "con-cerj", banca: "III", materia: "Direito Constitucional", peso: 2,
        tema: "Constituição do Estado do Rio de Janeiro",
        licoes: [] },
      { id: "con-leg", banca: "III", materia: "Direito Constitucional", peso: 2,
        tema: "Processo legislativo e repartição de competências",
        licoes: [] },
      { id: "con-trib", banca: "III", materia: "Direito Constitucional", peso: 2,
        tema: "Princípios constitucionais tributários",
        licoes: [] },
      { id: "con-mig", banca: "III", materia: "Direito Constitucional", peso: 1,
        tema: "Condição jurídica de estrangeiros e migrantes",
        questoes: ["gv-6"] },

      /* -------------- BANCA III · Direito Administrativo */
      { id: "adm-prin", banca: "III", materia: "Direito Administrativo", peso: 5,
        tema: "Princípios fundamentais e regime jurídico administrativo",
        questoes: ["adm-1", "prin-1", "prin-2", "prin-3"] },
      { id: "adm-resp", banca: "III", materia: "Direito Administrativo", peso: 5,
        tema: "Responsabilidade civil do Estado",
        licoes: ["administrativo-2"] },
      { id: "adm-atos", banca: "III", materia: "Direito Administrativo", peso: 4,
        tema: "Atos administrativos: atributos, invalidação e convalidação",
        questoes: ["ata-1", "ata-2", "ata-3"] },
      { id: "adm-controle", banca: "III", materia: "Direito Administrativo", peso: 4,
        tema: "Controle da Administração: interno, externo e judicial",
        questoes: ["prin-4", "prin-5"] },
      { id: "adm-serv", banca: "III", materia: "Direito Administrativo", peso: 3,
        tema: "Serviços públicos e delegação (concessões e permissões)",
        licoes: ["administrativo-1"] },
      { id: "adm-improb", banca: "III", materia: "Direito Administrativo", peso: 3,
        tema: "Improbidade administrativa (Lei 8.429 com a Lei 14.230/2021)",
        questoes: ["prin-7"] },
      { id: "adm-prop", banca: "III", materia: "Direito Administrativo", peso: 3,
        tema: "Intervenção do Estado na propriedade: desapropriação e servidões",
        licoes: [] },
      { id: "adm-agentes", banca: "III", materia: "Direito Administrativo", peso: 2,
        tema: "Agentes públicos e processo disciplinar",
        licoes: [] },
      { id: "adm-poderes", banca: "III", materia: "Direito Administrativo", peso: 2,
        tema: "Poderes da Administração: poder de polícia e discricionariedade",
        questoes: ["ata-6"] },
      { id: "adm-lic", banca: "III", materia: "Direito Administrativo", peso: 2,
        tema: "Licitações e contratos (Lei 14.133/2021)",
        questoes: ["ata-4", "ata-5"] },
      { id: "adm-proc", banca: "III", materia: "Direito Administrativo", peso: 2,
        tema: "Processo administrativo (Lei 9.784/99 e Lei estadual 5.427)",
        questoes: ["prin-6"] },
      { id: "adm-pol", banca: "III", materia: "Direito Administrativo", peso: 5,
        tema: "Políticas públicas setoriais: habitação e REURB, saúde, urbanismo, defesa civil, educação",
        licoes: [] },

      /* ------------------ BANCA III · Direitos Humanos */
      { id: "dh-desc", banca: "III", materia: "Direitos Humanos", peso: 5,
        tema: "Tutela coletiva, controle de políticas públicas, DESCs e judicialização",
        licoes: ["direitos-humanos-4"] },
      { id: "dh-fund", banca: "III", materia: "Direitos Humanos", peso: 5,
        tema: "Fundamentos filosóficos, teoria crítica, biopolítica e necropolítica",
        questoes: ["cri2-4"] },
      { id: "dh-didh", banca: "III", materia: "Direitos Humanos", peso: 5,
        tema: "Direito Internacional dos Direitos Humanos: fontes, gerações, responsabilidade internacional",
        licoes: ["direitos-humanos-1"] },
      { id: "dh-grupos", banca: "III", materia: "Direitos Humanos", peso: 5,
        tema: "Grupos vulnerabilizados, interseccionalidade e direito antidiscriminatório",
        licoes: ["direitos-humanos-2"] },
      { id: "dh-onu", banca: "III", materia: "Direitos Humanos", peso: 3,
        tema: "Sistema global de proteção (ONU)",
        licoes: ["direitos-humanos-3"] },
      { id: "dh-brasil", banca: "III", materia: "Direitos Humanos", peso: 3,
        tema: "Direitos humanos e o ordenamento brasileiro: hierarquia dos tratados e diálogo das cortes",
        questoes: ["trat-1", "trat-2", "trat-4", "trat-6"] },
      { id: "dh-tortura", banca: "III", materia: "Direitos Humanos", peso: 3,
        tema: "Direitos humanos e segurança pública: violência institucional, tortura, Protocolo de Istambul",
        questoes: ["dh-5", "sg-6"] },
      { id: "dh-sidh", banca: "III", materia: "Direitos Humanos", peso: 2,
        tema: "Sistema interamericano: Comissão e Corte IDH, procedimento e reparações",
        questoes: ["dh-2", "dh-3", "dh-4"] },
      { id: "dh-amb", banca: "III", materia: "Direitos Humanos", peso: 2,
        tema: "Direitos socioambientais e racismo ambiental",
        questoes: ["desc-7"] },
      { id: "dh-edh", banca: "III", materia: "Direitos Humanos", peso: 1,
        tema: "Educação em direitos humanos",
        questoes: ["desc-6"] },
      { id: "dh-def", banca: "III", materia: "Direitos Humanos", peso: 2,
        tema: "Defensores de direitos humanos e violência política",
        licoes: [] },
      { id: "dh-emp", banca: "III", materia: "Direitos Humanos", peso: 1,
        tema: "Empresas e direitos humanos",
        licoes: [] },

      /* ----- BANCA III · Princípios Institucionais da Defensoria */
      { id: "dpe-hist", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 5,
        tema: "Histórico, salaried staff, acesso à justiça, ondas renovatórias e modelos teóricos",
        licoes: ["defensoria-2"] },
      { id: "dpe-func", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 5,
        tema: "Funções institucionais (CF, LC 80/94, CE-RJ e LC estadual 06/1977)",
        questoes: ["dp-1", "dp-5"] },
      { id: "dpe-prer", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 5,
        tema: "Prerrogativas dos membros e a jurisprudência sobre elas",
        questoes: ["dp-4", "rec-4"] },
      { id: "dpe-gar", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 4,
        tema: "Garantias dos membros: independência funcional, inamovibilidade, irredutibilidade",
        licoes: [] },
      { id: "dpe-prin", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 3,
        tema: "Princípios institucionais e direitos dos assistidos",
        questoes: ["dp-2"] },
      { id: "dpe-pos", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 3,
        tema: "Posição constitucional, autonomia e essencialidade da Defensoria",
        questoes: ["dp-3", "aj-6"] },
      { id: "dpe-grat", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 2,
        tema: "Gratuidade × assistência judiciária × assistência jurídica",
        questoes: ["dp-6", "aj-3", "gj-1", "gj-2"] },
      { id: "dpe-disc", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 2,
        tema: "Deveres, proibições, impedimentos e regime disciplinar",
        licoes: [] },
      { id: "dpe-org", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 2,
        tema: "Estrutura e órgãos da DPERJ; carreira",
        licoes: [] },
      { id: "dpe-nat", banca: "III", materia: "Princípios Institucionais da Defensoria", peso: 2,
        tema: "Natureza jurídica da Defensoria e do Defensor Público",
        licoes: [] }
    ]
  },

  /* ==========================================================
     MPRJ — XXXIX Concurso (FGV)
     Pesos vindos do BACKLOG-EDITAL.md §4 e do cabeçalho do
     data-mprj.js (que dimensionou as lições pelos pesos do
     edital). O MAPA-MPRJ.md ainda não existe — quando o
     planejador-edital o escrever, revise os pontos aqui: os
     temas abaixo seguem as unidades da trilha, não as linhas
     do conteúdo programático.
     ========================================================== */
  "mprj": {
    fonte: "BACKLOG-EDITAL.md §4 + pesos declarados no data-mprj.js (MAPA-MPRJ.md pendente)",
    escala: "peso = peso da matéria no edital do XXXIX concurso (5, 3 ou 2)",
    pontos: [
      { id: "mp-pen-1", banca: "I", materia: "Direito Penal", peso: 5,
        tema: "Aplicação da lei penal e teoria do crime", licoes: ["mprj-penal-1"] },
      { id: "mp-pen-2", banca: "I", materia: "Direito Penal", peso: 5,
        tema: "Crimes contra a Administração Pública", licoes: ["mprj-penal-2"] },
      { id: "mp-cpp-1", banca: "I", materia: "Direito Processual Penal", peso: 5,
        tema: "Inquérito policial, ação penal e acordo de não persecução penal", licoes: ["mprj-cpp-1"] },
      { id: "mp-cpp-2", banca: "I", materia: "Direito Processual Penal", peso: 5,
        tema: "Provas, prisões e medidas cautelares", licoes: ["mprj-cpp-2"] },
      { id: "mp-lpe-1", banca: "I", materia: "Legislação Penal Extravagante", peso: 5,
        tema: "Lei de Drogas e violência doméstica", licoes: ["mprj-lpe-1"] },
      { id: "mp-lpe-2", banca: "I", materia: "Legislação Penal Extravagante", peso: 5,
        tema: "Hediondos, organização criminosa e execução penal", licoes: ["mprj-lpe-2"] },
      { id: "mp-civ-1", banca: "II", materia: "Direito Civil", peso: 5,
        tema: "Pessoas, negócio jurídico e prescrição", licoes: ["mprj-civil-1"] },
      { id: "mp-civ-2", banca: "II", materia: "Direito Civil", peso: 5,
        tema: "Família e sucessões", licoes: ["mprj-civil-2"] },
      { id: "mp-pc-1", banca: "II", materia: "Direito Processual Civil", peso: 5,
        tema: "Normas fundamentais, competência e o MP no processo", licoes: ["mprj-pcivil-1"] },
      { id: "mp-pc-2", banca: "II", materia: "Direito Processual Civil", peso: 5,
        tema: "Tutela provisória, sentença e recursos", licoes: ["mprj-pcivil-2"] },
      { id: "mp-emp", banca: "II", materia: "Direito Empresarial", peso: 2,
        tema: "Sociedades, falência e recuperação judicial", licoes: ["mprj-emp-1"] },
      { id: "mp-con-1", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Direitos fundamentais e organização do Estado", licoes: ["mprj-const-1"] },
      { id: "mp-con-2", banca: "III", materia: "Direito Constitucional", peso: 5,
        tema: "Controle de constitucionalidade e o MP na Constituição", licoes: ["mprj-const-2"] },
      { id: "mp-adm-1", banca: "III", materia: "Direito Administrativo", peso: 5,
        tema: "Atos, agentes públicos e responsabilidade do Estado", licoes: ["mprj-adm-1"] },
      { id: "mp-adm-2", banca: "III", materia: "Direito Administrativo", peso: 5,
        tema: "Licitações (Lei 14.133/21) e improbidade (Lei 14.230/21)", licoes: ["mprj-adm-2"] },
      { id: "mp-ele", banca: "III", materia: "Direito Eleitoral", peso: 3,
        tema: "Inelegibilidades, propaganda e crimes eleitorais", licoes: ["mprj-eleitoral-1"] },
      { id: "mp-trib", banca: "III", materia: "Direito Financeiro e Tributário", peso: 3,
        tema: "CTN, limitações ao poder de tributar e Lei de Responsabilidade Fiscal", licoes: ["mprj-tribut-1"] },
      { id: "mp-eca-1", banca: "IV", materia: "Direito da Infância e Juventude", peso: 5,
        tema: "Direitos fundamentais, poder familiar e adoção", licoes: ["mprj-eca-1"] },
      { id: "mp-eca-2", banca: "IV", materia: "Direito da Infância e Juventude", peso: 5,
        tema: "Ato infracional e medidas socioeducativas (SINASE)", licoes: ["mprj-eca-2"] },
      { id: "mp-tc-1", banca: "IV", materia: "Tutela Coletiva", peso: 5,
        tema: "Processo coletivo: LACP, CDC e coisa julgada", licoes: ["mprj-tc-1"] },
      { id: "mp-tc-2", banca: "IV", materia: "Tutela Coletiva", peso: 5,
        tema: "Inquérito civil, recomendação, TAC e improbidade", licoes: ["mprj-tc-2"] },
      { id: "mp-dif-amb", banca: "IV", materia: "Tutela Coletiva", peso: 5,
        tema: "Direito ambiental material: responsabilidade, licenciamento (LC 140), Código Florestal, Mata Atlântica, SNUC e resíduos",
        licoes: ["mprj-difusos-1"] },
      { id: "mp-dif-social", banca: "IV", materia: "Tutela Coletiva", peso: 5,
        tema: "Direitos sociais difusos: saúde e saúde mental (RAPS), políticas públicas e processo estrutural, educação, moradia",
        licoes: [] },
      { id: "mp-inst", banca: "IV", materia: "Princípios Institucionais do Ministério Público", peso: 5,
        tema: "O MP na CF/88: princípios, funções institucionais e poder investigatório", licoes: ["mprj-inst-1"] },
      { id: "mp-inst-lonmp", banca: "IV", materia: "Princípios Institucionais do Ministério Público", peso: 5,
        tema: "Lei Orgânica Nacional (8.625/93): órgãos, investidura do PGJ, CSMP, garantias, vedações e prerrogativas",
        licoes: ["mprj-inst-2"] },
      /* Declarado como lacuna: a LC-RJ 106/2003 não está no material do
         usuário, e a prova de 2025 cobra pontos específicos dela (Q94). Sem
         a lei, escrever questão seria inventar — o ponto fica visível no
         Diagnóstico com `licoes: []` até a fonte aparecer. */
      { id: "mp-inst-lomprj", banca: "IV", materia: "Princípios Institucionais do Ministério Público", peso: 4,
        tema: "Lei Orgânica do MPRJ (LC estadual 106/2003): estrutura, Órgão Especial, carreira e regime disciplinar",
        licoes: [] }
    ]
  },

  /* ==========================================================
     ENAM — Exame Nacional da Magistratura
     SEM peso: não existe mapa de banca da ENAM neste projeto, e
     peso inventado estragaria justamente o número que dá sentido
     ao diagnóstico. Com `peso: null` o app ranqueia estes pontos
     só pelo seu desempenho e avisa isso na tela. Há item aberto
     no BACKLOG-EDITAL.md para apurar o peso real a partir das 6
     edições da ENAM.
     ========================================================== */
  "enam": {
    fonte: "estrutura dos 8 blocos fixos da FGV (data-enam.js) — peso de edital ainda não apurado",
    escala: "sem peso mapeado: o ranking usa só o seu desempenho",
    pontos: [
      { id: "en-con-1", banca: "enam", materia: "Direito Constitucional", peso: null,
        tema: "Controle de constitucionalidade", licoes: ["enam-const-1"] },
      { id: "en-con-2", banca: "enam", materia: "Direito Constitucional", peso: null,
        tema: "Direitos e garantias fundamentais", licoes: ["enam-const-2"] },
      { id: "en-con-3", banca: "enam", materia: "Direito Constitucional", peso: null,
        tema: "Poder constituinte e tratados", licoes: ["enam-const-3"] },
      { id: "en-adm-1", banca: "enam", materia: "Direito Administrativo", peso: null,
        tema: "Princípios, atos e controle judicial", licoes: ["enam-adm-1"] },
      { id: "en-adm-2", banca: "enam", materia: "Direito Administrativo", peso: null,
        tema: "Licitações, improbidade e controle externo", licoes: ["enam-adm-2"] },
      { id: "en-adm-3", banca: "enam", materia: "Direito Administrativo", peso: null,
        tema: "Serviços públicos e poder de polícia", licoes: ["enam-adm-3"] },
      { id: "en-adm-4", banca: "enam", materia: "Direito Administrativo", peso: null,
        tema: "Responsabilidade civil do Estado", licoes: ["enam-adm-4"] },
      { id: "en-hum-1", banca: "enam", materia: "Formação Humanística", peso: null,
        tema: "Precedentes, hermenêutica e acesso à justiça", licoes: ["enam-hum-1"] },
      { id: "en-hum-2", banca: "enam", materia: "Formação Humanística", peso: null,
        tema: "Gênero, raça e sociologia jurídica", licoes: ["enam-hum-2"] },
      { id: "en-dh-1", banca: "enam", materia: "Direitos Humanos", peso: null,
        tema: "Sistema Interamericano e controle de convencionalidade", licoes: ["enam-dh-1"] },
      { id: "en-dh-2", banca: "enam", materia: "Direitos Humanos", peso: null,
        tema: "Sistema global da ONU", licoes: ["enam-dh-2"] },
      { id: "en-dh-3", banca: "enam", materia: "Direitos Humanos", peso: null,
        tema: "Grupos vulnerabilizados e igualdade", licoes: ["enam-dh-3"] },
      { id: "en-dh-4", banca: "enam", materia: "Direitos Humanos", peso: null,
        tema: "DESC e políticas públicas", licoes: ["enam-dh-4"] },
      { id: "en-pc-1", banca: "enam", materia: "Direito Processual Civil", peso: null,
        tema: "Gratuidade, provas e tutela provisória", licoes: ["enam-pc-1"] },
      { id: "en-pc-2", banca: "enam", materia: "Direito Processual Civil", peso: null,
        tema: "Coisa julgada e rescisória", licoes: ["enam-pc-2"] },
      { id: "en-pc-3", banca: "enam", materia: "Direito Processual Civil", peso: null,
        tema: "Recursos, reclamação e remessa necessária", licoes: ["enam-pc-3"] },
      { id: "en-pc-4", banca: "enam", materia: "Direito Processual Civil", peso: null,
        tema: "Tutela coletiva e ação civil pública", licoes: ["enam-pc-4"] },
      { id: "en-pc-5", banca: "enam", materia: "Direito Processual Civil", peso: null,
        tema: "Execução, penhora e possessórias", licoes: ["enam-pc-5"] },
      { id: "en-civ-1", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Parte geral, capacidade e personalidade", licoes: ["enam-civil-1"] },
      { id: "en-civ-2", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Obrigações, contratos e responsabilidade civil", licoes: ["enam-civil-2"] },
      { id: "en-civ-3", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Família e regime de bens", licoes: ["enam-civil-3"] },
      { id: "en-civ-4", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Sucessões", licoes: ["enam-civil-4"] },
      { id: "en-civ-5", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Direitos reais, condomínio e vizinhança", licoes: ["enam-civil-5"] },
      { id: "en-civ-6", banca: "enam", materia: "Direito Civil", peso: null,
        tema: "Consumidor e proteção de dados", licoes: ["enam-civil-6"] },
      { id: "en-emp-1", banca: "enam", materia: "Direito Empresarial", peso: null,
        tema: "Títulos de crédito e locação empresarial", licoes: ["enam-emp-1"] },
      { id: "en-emp-2", banca: "enam", materia: "Direito Empresarial", peso: null,
        tema: "Sociedades e recuperação judicial", licoes: ["enam-emp-2"] },
      { id: "en-pen-1", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Teoria geral do crime", licoes: ["enam-penal-1"] },
      { id: "en-pen-2", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Crimes contra o patrimônio", licoes: ["enam-penal-2"] },
      { id: "en-pen-3", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Crimes contra a Administração Pública", licoes: ["enam-penal-3"] },
      { id: "en-pen-4", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Crimes contra a dignidade sexual", licoes: ["enam-penal-4"] },
      { id: "en-pen-5", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Dosimetria, pena e prescrição", licoes: ["enam-penal-5"] },
      { id: "en-pen-6", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Crimes em espécie e leis especiais", licoes: ["enam-penal-6"] },
      { id: "en-pen-7", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Processo penal: prisões, competência e júri", licoes: ["enam-penal-7"] },
      { id: "en-pen-8", banca: "enam", materia: "Direito Penal", peso: null,
        tema: "Criminologia", licoes: ["enam-penal-8"] }
    ]
  }
};
